# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: measurements.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12measurements.proto\x12\x06specio\"9\n\rSpectralShape\x12\r\n\x05start\x18\x01 \x01(\x01\x12\x0b\n\x03\x65nd\x18\x02 \x01(\x01\x12\x0c\n\x04step\x18\x03 \x01(\x01\"|\n\x14SpectralDistribution\x12$\n\x05shape\x18\x01 \x01(\x0b\x32\x15.specio.SpectralShape\x12\x0e\n\x06values\x18\x02 \x03(\x01\x12\x12\n\nvalues_old\x18\x04 \x03(\x02\x12\x11\n\x04name\x18\x03 \x01(\tH\x00\x88\x01\x01\x42\x07\n\x05_name\",\n\tXYZ_value\x12\t\n\x01X\x18\x01 \x01(\x01\x12\t\n\x01Y\x18\x02 \x01(\x01\x12\t\n\x01Z\x18\x03 \x01(\x01\" \n\x08xy_value\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\"%\n\tcct_value\x12\x0b\n\x03\x63\x63t\x18\x01 \x01(\x01\x12\x0b\n\x03\x64uv\x18\x02 \x01(\x01\"\x1c\n\tTimestamp\x12\x0f\n\x07timestr\x18\x01 \x01(\t\"\x8c\x02\n\x0bMeasurement\x12)\n\x03spd\x18\x01 \x01(\x0b\x32\x1c.specio.SpectralDistribution\x12\x10\n\x08\x65xposure\x18\x02 \x01(\x01\x12\x1e\n\x03XYZ\x18\x03 \x01(\x0b\x32\x11.specio.XYZ_value\x12\x1c\n\x02xy\x18\x04 \x01(\x0b\x32\x10.specio.xy_value\x12\x1e\n\x03\x63\x63t\x18\x05 \x01(\x0b\x32\x11.specio.cct_value\x12\x13\n\x0b\x64ominant_wl\x18\x06 \x01(\x01\x12\r\n\x05power\x18\x07 \x01(\x01\x12\x17\n\x0fspectrometer_id\x18\x08 \x01(\t\x12\x1f\n\x04time\x18\t \x01(\x0b\x32\x11.specio.TimestampJ\x04\x08\x10\x10\x11\"\xfc\x01\n\x0fMeasurementList\x12)\n\x0cmeasurements\x18\x01 \x03(\x0b\x32\x13.specio.Measurement\x12\x36\n\x0btest_colors\x18\x03 \x03(\x0b\x32!.specio.MeasurementList.TestColor\x12\r\n\x05order\x18\x02 \x03(\x05\x12\r\n\x05notes\x18\x10 \x01(\t\x12\x0e\n\x06\x61uthor\x18\x11 \x01(\t\x12\x10\n\x08location\x18\x12 \x01(\t\x12\x10\n\x08software\x18\x13 \x01(\t\x12\x11\n\tancillary\x18\x14 \x01(\x0c\x1a!\n\tTestColor\x12\t\n\x01\x63\x18\x01 \x03(\r\x12\t\n\x01\x66\x18\x02 \x03(\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'measurements_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_SPECTRALSHAPE']._serialized_start=30
  _globals['_SPECTRALSHAPE']._serialized_end=87
  _globals['_SPECTRALDISTRIBUTION']._serialized_start=89
  _globals['_SPECTRALDISTRIBUTION']._serialized_end=213
  _globals['_XYZ_VALUE']._serialized_start=215
  _globals['_XYZ_VALUE']._serialized_end=259
  _globals['_XY_VALUE']._serialized_start=261
  _globals['_XY_VALUE']._serialized_end=293
  _globals['_CCT_VALUE']._serialized_start=295
  _globals['_CCT_VALUE']._serialized_end=332
  _globals['_TIMESTAMP']._serialized_start=334
  _globals['_TIMESTAMP']._serialized_end=362
  _globals['_MEASUREMENT']._serialized_start=365
  _globals['_MEASUREMENT']._serialized_end=633
  _globals['_MEASUREMENTLIST']._serialized_start=636
  _globals['_MEASUREMENTLIST']._serialized_end=888
  _globals['_MEASUREMENTLIST_TESTCOLOR']._serialized_start=855
  _globals['_MEASUREMENTLIST_TESTCOLOR']._serialized_end=888
# @@protoc_insertion_point(module_scope)
